---

version: "3.9"


networks:
    proxy:
        driver: overlay
    database:
        driver: overlay


configs:
    NGINX_SITE_V2:
        file: ./configs/default.conf


secrets:
    MYSQL_ROOT_PASSWORD:
        file: ./secrets/MYSQL_ROOT_PASSWORD
    MYSQL_FOODINI_PASSWORD:
        file: ./secrets/MYSQL_FOODINI_PASSWORD
    NGINX_SSL_CERT_V1:
        file: ./secrets/cert.pem
    NGINX_SSL_KEY_V1:
        file: ./secrets/key.pem
    FOODINI_API_SECRET_KEY_V1:
        file: ./secrets/FOODINI_API_SECRET_KEY_V1


services:
    mariadb:
        image: mariadb:10.8.3-jammy
        environment:
            - TZ=Europe/Amsterdam
            - MYSQL_DATABASE=foodini
            - MYSQL_USER=foodini
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
            - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_USER_PASSWORD
        secrets:
            - source: MYSQL_ROOT_PASSWORD
              target: MYSQL_ROOT_PASSWORD
            - source: MYSQL_FOODINI_PASSWORD
              target: MYSQL_USER_PASSWORD
        volumes:
            - type: bind
              source: /data/database/storage/
              target: /var/lib/mysql/
              read_only: false
        networks:
            database:
                aliases:
                    - database

    adminer:
        image: adminer:4.8.1-standalone
        environment:
            - TZ=Europe/Amsterdam
            - ADMINER_DEFAULT_SERVER=database
        networks:
            - database
            - proxy

    foodini_api:
        image: foodini:0.2.0
        environment:
            CORS_ORIGINS: '["http://localhost:8080"]'
        secrets:
            - source: MYSQL_FOODINI_PASSWORD
              target: DATABASE_PASS
            - source: FOODINI_API_SECRET_KEY_V1
              target: SECRET_KEY
        networks:
            - database
            - proxy

    nginx:
        image: nginx:1.21.6-alpine
        environment:
            - TZ=Europe/Amsterdam
        configs:
            - source: NGINX_SITE_V2
              target: /etc/nginx/conf.d/default.conf
        secrets:
            - source: NGINX_SSL_CERT_V1
              target: cert
            - source: NGINX_SSL_KEY_V1
              target: key
        networks:
            - proxy
        ports:
            - published: 80
              target: 80
              protocol: tcp
              mode: host
            - published: 443
              target: 443
              protocol: tcp
              mode: host
