---

version: "3.9"


services:
    foodini_api:
        image: foodini:0.2.0-dev
        environment:
            - RELOAD=True
            - DEBUG=True
        volumes:
            - type: bind
              source: ./foodini/
              target: /app/
              read_only: false
