"""Initial

Revision ID: b9857bd62308
Revises:
Create Date: 2022-05-24 20:31:40.540350

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b9857bd62308'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user = op.create_table('user',
                           sa.Column('id', sa.Integer(), nullable=False),
                           sa.Column('username', sa.String(length=256), nullable=False),
                           sa.Column('first_name', sa.String(length=256), nullable=False),
                           sa.Column('last_name', sa.String(length=256), nullable=False),
                           sa.Column('admin', sa.Boolean(), nullable=False),
                           sa.Column('active', sa.Boolean(), nullable=False),
                           sa.Column('hashed_password', sa.CHAR(length=60), nullable=False),
                           sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                           sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                           sa.PrimaryKeyConstraint('id'),
                           sa.UniqueConstraint('username')
                           )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('recipe',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('method_of_preperation', sa.Text(), nullable=False),
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_recipe_id'), 'recipe', ['id'], unique=False)
    op.create_table('ingredient',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('optional', sa.Boolean(), nullable=False),
                    sa.Column('comment', sa.String(length=256), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('recipe_id', 'name')
                    )
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(user, [
        {
            "username": "MasterChief",
            "first_name": "Master",
            "last_name": "Chief",
            "admin": True,
            "active": True,
            "hashed_password": "$2b$12$d7JICUO1feNuZjK5sHbVUey7mid5UxG34W098zYMb/yytay0tnlEW"
        }
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_recipe_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
